name: Expiration Checks

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: reserve
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python expirationchecks.py
      - name: Push auto-fixed files
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name 'ExpirationChecks[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "🚿 Delete expired translations by github-actions"; \
            git push origin reserve; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
